### ISSUE TITLE
Logo de baja calidad

### ISSUE THREAD

**Issue by maxiyommi** [mecantronic/mecantronic-page#5]
En la ruta: http://localhost:3000/servicios/2

![image](https://github.com/githubmec/mecantronic-page/assets/24780670/73e27c3e-43f0-4aaf-b94a-ff511668c7a3)

**Comment by RodrigoQuaglia** [comment]
Adjunto Logo de Orsai en SVG
![Logo Orsai SVG](https://github.com/mecantronic/mecantronic-page/assets/133234380/cc763032-999d-4026-b65e-0e719bf4127d)

PD: No se ven las primeras letras por están en negro.

**Comment by RodrigoQuaglia** [comment]
**Adjunto Logo de Uali en SVG para reemplazar:**

![Logo Uali](https://github.com/mecantronic/mecantronic-page/assets/133234380/532dbc87-d164-4781-80ca-c2f87c05665c)

Revisar si este logo arregla el issue del borde del logo
